version: 2

models:
  - name: dim_listing_cleansed
    description: Cleansed table which contains Airbnb listings.
    
    columns: 
     
     - name: listing_id
       description: Primary key for listing
       tests:
         - unique
         - not_null
     
     - name: host_id
       description: The host's id. references to the host table.
       tests:
         - not_null
         - relationships:
            to: ref('dim_host_cleansed')
            field: host_id
     
     - name: room_type
       description: The type of appartment/room
       tests:
         - accepted_values:
            values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']

     - name: minimum_nights
       tests:
         - positive_value
