version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifiers: raw_listings
      
      - name: hosts
        identifiers: raw_hosts

      - name: reviews
        identifiers: raw_reviews